/**
 * Published ink detections — Vesuvius Challenge's, not ours.
 *
 * WHAT THESE ARE. Each one is a raster: a model's per-pixel score for "is there
 * ink here", computed on a flattened surface volume and published as a full-res
 * TIFF plus a downsampled JPEG. It is the *output* of a detector, not a
 * detector. Nothing here runs a model; nothing here draws a letter. The
 * pipeline is: fetch their JPEG, threshold it, recolour it, composite it.
 *
 * WHOSE THEY ARE. Every map carries the name of the model that produced it,
 * parsed out of their own filename. That name is shown with the overlay and is
 * not optional — an overlay you cannot attribute is one that looks like a claim
 * we are making. Scroll data is CC BY-NC 4.0, © Vesuvius Challenge.
 *
 * WHAT IS NOT REDISTRIBUTED. This module holds URLs. The browser reads the
 * public bucket directly (verified `Access-Control-Allow-Origin: *`), so no
 * scroll pixels live in this repo and the read path stays client-side.
 *
 * WHY PLACEMENT NEEDS NO REGISTRATION. The map is drawn on the surface volume's
 * own canvas, so an overlay pixel maps to the sheet by a pure scale. The scale
 * is measured, never assumed: `canvas[0] / image.width`. The true factor is
 * 8.0006, not 8, and baking 8 drifts the overlay by about a letter width across
 * a 30,000-pixel sheet.
 *
 * Catalog generated by tools/build_ink_catalog.py -> public/ink-maps.json.
 */

export type InkMap = {
  /** Model that produced this map, from the published filename. */
  model: string;
  /** ds8 JPEG on the public bucket. */
  url: string;
};

export type InkSheet = {
  id: string;
  scroll: string;
  segment: string;
  /** Surface volume the map was computed on. */
  volume: string;
  url: string;
  voxelUm: number;
  /** [layers, y, x] at level 0. */
  shape: [number, number, number];
  /** [x, y] at level 0 — the canvas the map is drawn on. */
  canvas: [number, number];
  maps: InkMap[];
};

export type InkCatalog = {
  note: string;
  sheets: number;
  maps: number;
  scrolls: string[];
  entries: InkSheet[];
};

let pending: Promise<InkCatalog | null> | null = null;

/** Fetch once per page load; a failure is cached as null, not retried forever. */
export function loadInkCatalog(): Promise<InkCatalog | null> {
  if (!pending) {
    pending = fetch("/ink-maps.json")
      .then((r) => (r.ok ? (r.json() as Promise<InkCatalog>) : null))
      .catch(() => null);
  }
  return pending;
}

/**
 * The sheet whose surface volume this specimen URL points at.
 *
 * Matched on the volume URL rather than on the segment, because a segment can
 * carry several flattenings and each has its own map. Matching on segment alone
 * would put a 59 keV map on a 78 keV sheet — the same class of error as
 * assuming the downsample factor.
 */
export function sheetForVolume(
  catalog: InkCatalog | null,
  volumeUrl: string,
): InkSheet | undefined {
  return catalog?.entries.find((e) => e.url === volumeUrl);
}

/**
 * Default threshold: the top decile of the map's own non-zero scores.
 *
 * This is the cutoff the Scroll 1 positive control passed at, so it stays the
 * default — a viewer that opens at some other cutoff is not showing the thing
 * that was verified. Zero is off-sheet (the maps are masked), and counting it
 * drags the percentile down onto background.
 */
export function topDecile(gray: Uint8ClampedArray): number {
  const hist = new Uint32Array(256);
  let n = 0;
  for (let i = 0; i < gray.length; i += 4) {
    const v = gray[i];
    if (v === 0) continue;
    hist[v]++;
    n++;
  }
  if (n === 0) return 128;
  const target = n * 0.9;
  let seen = 0;
  for (let v = 0; v < 256; v++) {
    seen += hist[v];
    if (seen >= target) return v;
  }
  return 255;
}
