#!/usr/bin/env python3
"""Emit lib/surfaces.ts entries for every PHerc0139 segment we have labels for.

Why this is the join. The published ink map is written on the surface volume's
own canvas: measured, canvas_size == the surface volume's [y, x] at level 0
(59 keV ds8 map 10501 px wide x8 = 84008, against a canvas_size of 84010). So a
pixel in our label raster maps to the sheet by a pure scale:

    surface_level0_xy = label_ds8_xy * 8 * png_downsample

No registration, no guesswork -- the same grid the labels were computed on.
That is what lets a click on /qc open the viewer at the papyrus underneath.

    python3 tools/build_surface_catalog.py
"""
import json, os, re, urllib.request

B = "https://vesuvius-challenge-open-data.s3.us-east-1.amazonaws.com"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UA = {"User-Agent": "Mozilla/5.0"}
SCROLL = "PHerc0139"


def get(u):
    return urllib.request.urlopen(
        urllib.request.Request(u, headers=UA), timeout=60).read()


def listing(prefix, delim="/"):
    x = get(f"{B}/?list-type=2&prefix={prefix}&max-keys=1000"
            + (f"&delimiter={delim}" if delim else "")).decode()
    tag = "Prefix" if delim else "Key"
    return [p for p in re.findall(rf"<{tag}>([^<]*)</{tag}>", x) if p != prefix]


def main():
    idx = json.load(open(os.path.join(ROOT, "public", "qc", "index.json")))
    want = {s["segment"] for s in idx["segments"]}
    segs = listing(f"{SCROLL}/segments/")
    out, misses = [], []

    for segpath in segs:
        full = segpath.rstrip("/").split("/")[-1]
        short = full[:14]
        if short not in want:
            continue
        vols = listing(f"{segpath}surface-volumes/")
        # the L1 flattening the 59 keV ink map was computed on
        pick = [v for v in vols if "1.129um" in v and "-L1.zarr" in v]
        if not pick:
            misses.append(short)
            continue
        name = pick[0].rstrip("/").split("/")[-1]
        try:
            za = json.loads(get(f"{B}/{pick[0]}0/.zarray").decode())
            shape = za["shape"]
        except Exception as e:
            misses.append(f"{short} ({e})")
            continue
        out.append(dict(short=short, full=full, name=name, shape=shape))
        print(f"  {short}  {shape}  {name[:44]}")

    ts = []
    for e in out:
        ts.append(f'''  {{
    id: "0139-{e["short"]}",
    scroll: "{SCROLL}",
    segment: "{e["full"]}",
    label: "PHerc0139 · seg {e["short"]} · 2.258 µm (L1)",
    url: surface(
      "{SCROLL}",
      "{e["full"]}",
      "{e["name"]}",
    ),
    voxelUm: 2.258,
    shape: [{e["shape"][0]}, {e["shape"][1]}, {e["shape"][2]}],
    note: "Cross-scan labels exist for this segment — see /qc.",
  }},''')

    p = os.path.join(ROOT, "lib", "surfaces.generated.ts")
    open(p, "w").write(
        "// GENERATED by tools/build_surface_catalog.py — do not edit by hand.\n"
        "// The 59 keV L1 flattening each PHerc0139 ink map was computed on, so\n"
        "// label coordinates map to these volumes by a pure scale.\n"
        "import type { SurfaceEntry } from \"./surfaces\";\n\n"
        "export function build0139(\n"
        "  surface: (scroll: string, segment: string, vol: string) => string,\n"
        "): SurfaceEntry[] {\n  return [\n" + "\n".join(ts) + "\n  ];\n}\n")
    print(f"\n{len(out)} segments -> {p}")
    if misses:
        print("no usable L1 surface volume:", misses)


if __name__ == "__main__":
    main()
